version: "3.8"
services:
  mysql:
    restart: always
    image: mysql:8.1
    container_name: gotutor-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-hello123
      MYSQL_PASSWORD: secret-hello123
      MYSQL_DATABASE: database
      MYSQL_USER: user
    healthcheck:
      test: ["CMD", "mysqladmin", "ping",  "-u", "user", "--password=secret-hello123"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ./mysql/data:/var/lib/mysql