version: "3.8"
services:
  mysql:
    restart: always
    image: mysql:8.1
    container_name: gotutor-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-hello123
      MYSQL_PASSWORD: secret-hello123
      MYSQL_DATABASE: database
      MYSQL_USER: user
    volumes:
      - ./mysql/data:/var/lib/mysql